// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA18FjMBnwJgrV5zzVa5NEyqtCrdq17B9Y',
    appId: '1:126679348688:web:1fbcb551d751f5970975d5',
    messagingSenderId: '126679348688',
    projectId: 'movie-app-route-7ba67',
    authDomain: 'movie-app-route-7ba67.firebaseapp.com',
    storageBucket: 'movie-app-route-7ba67.firebasestorage.app',
    measurementId: 'G-SBWK8MC81V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpneODJ6-ii5a0nark_vFa17z7SyGjio',
    appId: '1:126679348688:android:f2d323b4c8b657c10975d5',
    messagingSenderId: '126679348688',
    projectId: 'movie-app-route-7ba67',
    storageBucket: 'movie-app-route-7ba67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhf1Bqyiv811te94ugWlP8Zk9PjPXRv0',
    appId: '1:126679348688:ios:964cd5562181011e0975d5',
    messagingSenderId: '126679348688',
    projectId: 'movie-app-route-7ba67',
    storageBucket: 'movie-app-route-7ba67.firebasestorage.app',
    iosBundleId: 'com.example.routemovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnhf1Bqyiv811te94ugWlP8Zk9PjPXRv0',
    appId: '1:126679348688:ios:964cd5562181011e0975d5',
    messagingSenderId: '126679348688',
    projectId: 'movie-app-route-7ba67',
    storageBucket: 'movie-app-route-7ba67.firebasestorage.app',
    iosBundleId: 'com.example.routemovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA18FjMBnwJgrV5zzVa5NEyqtCrdq17B9Y',
    appId: '1:126679348688:web:ed7fabb46b27fd780975d5',
    messagingSenderId: '126679348688',
    projectId: 'movie-app-route-7ba67',
    authDomain: 'movie-app-route-7ba67.firebaseapp.com',
    storageBucket: 'movie-app-route-7ba67.firebasestorage.app',
    measurementId: 'G-67D721J4XQ',
  );
}
